# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

executors:
  nodejs:
    docker:
      - image: circleci/node:12.16

jobs:
  nexploit-test:
    executor: nodejs
    working_directory: ~/project

    steps:
      - setup_remote_docker
      - run:
          name: Install nexploit-cli
          command: |
            sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
      - run:
          name: Check nexploit-cli version
          command: |
            nexploit-cli --version
      - run:
          name: Run nexploit repeater
          command: |
            docker pull neuralegion/repeater
            docker run -d neuralegion/repeater repeater --id $REPEATER --token $NEXPLOIT_TOKEN
      - run: sleep 10
      - run:
          name: Show docker containers
          command: |
            docker ps -a
      - run:
          name: Start Nexploit Scan 🏁
          command: |
            SCAN_ID=$(nexploit-cli scan:run                                                 \
              --project $PROJECT_ID                             \
              --name "NexploitTestApp for a '<< pipeline.git.branch >>' branch #<< pipeline.number >>" \
              --archive $FILE_ID                                    \
              --repeater $REPEATER                                            \
              --token $NEXPLOIT_TOKEN)
            echo export SCAN_ID=$SCAN_ID >> "$BASH_ENV"
      - run:
          name: Get the output scan url 🔗
          command: |
            printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
      - run:
          name: Wait for issues ⏳
          command: |
            nexploit-cli scan:polling               \
              --interval 30s                        \
              --timeout 4m                         \
              --token $NEXPLOIT_TOKEN \
              --breakpoint high_issue $SCAN_ID
      - run:
          name: Stop Scan on Fail 🛑
          when: on_fail
          command: |
            echo "Canceling workflow as a step resulted in failure"
            [[ ! -z ${SCAN_ID+z} ]] && nexploit-cli scan:stop --token $NEXPLOIT_TOKEN $SCAN_ID || true
      
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: '16.10'
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
      - nexploit-test:
          name: 'nexploit-test'
