# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

executors:
  nodejs:
    docker:
      - image: circleci/node:12.16

jobs:
  nexploit-test:
    executor: nodejs
    working_directory: ~/project

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install nexploit-cli
          command: |
            sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
      - run:
          name: Check nexploit-cli version
          command: |
            nexploit-cli --version
      - run:
          name: Docker Repeater
          command: |
            docker pull neuralegion/repeater
            docker run neuralegion/repeater -v
            docker run -d neuralegion/repeater repeater --id $REPEATER --token $NEXPLOIT_TOKEN
      - run: sleep 10
      - run:
          name: Show docker ps
          command: |
            docker ps -a

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: '16.10'
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
      - nexploit-test:
          name: 'nexploit-test'
