name: CI

on:
  push:
    branches:
      - master

jobs:
  start_and_wait_scan:
    runs-on: ubuntu-18.04
    name: A job to run a Nexploit scan
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt update
          sudo apt-get install nodejs-dev node-gyp libssl1.0-dev
          sudo apt-get install nodejs npm
          sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
      - name: Docker Repeater
        run: |
          sudo docker pull neuralegion/repeater
          sudo docker run neuralegion/repeater -v
          sudo docker run neuralegion/repeater repeater --id ${{ secrets.REPEATER }} --token ${{ secrets.NEXPLOIT_TOKEN }} > /dev/null & echo $!
      - run: sleep 30s
      - name: Start Nexploit Scan 🏁
        id: start
        run: |
          SCAN_ID=$(nexploit-cli scan:run                                                 \
            --project ${{ secrets.PROJECT_ID }}                             \
            --name "NexploitTestApp for a '${GITHUB_REF##*/}' branch #${GITHUB_RUN_NUMBER}" \
            --archive ${{ secrets.FILE_ID }}                                    \
            --repeater ${{ secrets.REPEATER }}                                            \
            --token ${{ secrets.NEXPLOIT_TOKEN }})
          echo "SCAN_ID=$SCAN_ID" >> $GITHUB_ENV
      - name: Get the output scan url 🔗
        run: |
          printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID"
      - name: Wait for issues ⏳
        run: |
          nexploit-cli scan:polling               \
            --interval 30s                        \
            --timeout 4m                         \
            --token ${{ secrets.NEXPLOIT_TOKEN }} \
            --breakpoint high_issue $SCAN_ID
      - name: Stop Scan 🛑
        continue-on-error: true
        if: ${{ always() }}
        run: nexploit-cli scan:stop --token ${{ secrets.NEXPLOIT_TOKEN }} $SCAN_ID
